name: Deploy API

on:
  push:
    branches:
      - main
    paths:
      - todo-list-api/**

jobs:
  Deploy-API:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-list-api
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get .

      - name: Run build
        run: GOOS=linux go build -v -a -o main main.go

      - name: Create archive
        run: zip todo-list.zip main && ls -la

      - name: Deploy to AWS Lambda
        uses: yvesgurcan/deploy-lambda-function
        with:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          function-name: todo-list-api
          package: todo-list.zip
